### ISSUE TITLE
Disqusが機能していない

### ISSUE THREAD

**Issue by k-takata** [vim-jp/vim-users-jp#10]
各記事のDisqusウィジェットが機能していません。
こうでしょうか？

``` diff
--- a/_config.yml
+++ b/_config.yml
@@ -1,5 +1,6 @@
 markdown: rdiscount
 encoding: utf-8
+base-url: http://vim-jp.org/vim-users-jp
 exclude:
   - 'scripts'
   - '_original'
```

よく分かっていません。

**Comment by mattn** [comment]
モデレータ(私)によって確認されるまでコメントは表示されません。

On 12/1/14, K.Takata notifications@github.com wrote:

> 各記事のDisqusウィジェットが機能していません。
> こうでしょうか？
> 
> ``` diff
> --- a/_config.yml
> +++ b/_config.yml
> @@ -1,5 +1,6 @@
>  markdown: rdiscount
>  encoding: utf-8
> +base-url: http://vim-jp.org/vim-users-jp
>  exclude:
>    - 'scripts'
>    - '_original'
> ```
> 
> よく分かっていません。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/vim-jp/vim-users-jp/issues/10

## 
- Yasuhiro Matsumoto

**Comment by k-takata** [comment]
そもそもコメントの入力欄が表示されていません。
"We were unable to load Disqus. If you are a moderator please see our troubleshooting guide." と表示されています。

**Comment by mattn** [comment]
あざます

**Comment by k-takata** [comment]
入力欄が表示されているのを確認しました。
