### ISSUE TITLE
vim-jp のサイトがダサい

### ISSUE THREAD

**Issue by mattn** [vim-jp/vim-users-jp#11]
以下省略

参考文献: 

<blockquote class="twitter-tweet" lang="en"><p><a href="https://twitter.com/mattn_jp">@mattn_jp</a> そのissue、vim-jpにも作ろう!</p>&mdash; MURAOKA Taro (@kaoriya) <a href="https://twitter.com/kaoriya/status/568638316628680706">February 20, 2015</a></blockquote>

**Comment by k-takata** [comment]
なぜ vim-users-jp リポジトリに？というつっこみはOKですか？

**Comment by mattn** [comment]
まちがった！
