### ISSUE TITLE
Google Prettify を入れるべきか

### ISSUE THREAD

**Issue by mattn** [vim-jp/vim-users-jp#4]
現状、code 部に色がないので Google Prettify を入れてみてはどうかと思いますが、どうでしょう？

**Comment by thinca** [comment]
:+1:

**Comment by mattn** [comment]
ひとまず Google Code Prettify 入れたけど class が lang-vim じゃないのでガン無視されている。

**Comment by thinca** [comment]
つらみ。

**Comment by k-takata** [comment]
Google Code Prettify は Vim script に対応しているのでしょうか。

**Comment by mattn** [comment]
@hail2u さんがやってますね。

**Comment by k-takata** [comment]
あー、把握。 https://github.com/hail2u/google-code-prettify-language-handlers を使っているのですね。

**Comment by k-takata** [comment]
ちゃんと動いていなかったようなので、修正しておきました。

`<pre class="prettyprint lang-vim"><code> ～ </code></pre>` にすれば色が付くことは、ローカルで確認しました。

**Comment by mattn** [comment]
github は text/plain しかサーブしないみたいで動いてなかったので直しました。

**Comment by hail2u** [comment]
`lang-vim`はGoogle Code Prettifyの特殊なクラスなので、[HTML5仕様書の`code`要素の項](http://www.w3.org/TR/html5/text-level-semantics.html#the-code-element)で触れられてるような`code`へ`language-vim`を振る形の方が良いかも。Google Code Prettifyではサポートされてる。

``` html
<pre class="prettyprint"><code class="language-vim">...</code></pre>
```

仮に将来他の構文強調ツールに乗り換えるとなった時にサポートされてる可能性が一番高いかなーと思う。[Prism](http://prismjs.com/)（MDNで使われてる奴）とか[Rainbow](http://craig.is/making/rainbows)（まぁまぁ速い）とか。

僕のウェブサイトではクリーンな状態でHTMLを保持しときたかったので、`pre`要素に`prettyprint`クラスとかもあらかじめ振らないで、もうちょっと複雑に`prettyPrint()`を[呼んでる](https://gist.github.com/hail2u/ca89d61c394c7dc1dbf7#file-prettify-loader-js)。こっちは趣味の領域かも。

**Comment by mattn** [comment]
ひとまず lang-vim にはしました。

``` vim
let text = substitute(text, '\(<pre>\s*\)\@<!<code[^>]*>.\{-}</code>', '<pre class="prettyprint">&</pre>', 'g')
```

も入れようかと思いましたがちょっとやり過ぎ(inline elementがblock elementになる)かなと思ったのでやめました。

**Comment by mattn** [comment]
色付きました。
一旦閉じます。
