### ISSUE TITLE
修正方針

### ISSUE THREAD

**Issue by mattn** [vim-jp/vim-users-jp#5]
README.md を置くのもどうかと思ったのでこちらで。
- 基本 _original は触らない(再度取得し直す可能性がある)
- _post も触らない(スクリプト変換で生成)

**Comment by thinca** [comment]
この Issue は何を目的とした Issue で、どのようになったら Close されるのでしょう?

**Comment by mattn** [comment]
ひとまず議論の場として作成しました。
何も意見がないという事で閉じますね。

**Comment by k-takata** [comment]
> README.md を置くのもどうかと思ったのでこちらで。

置いちゃってもいいんじゃないでしょうか。
あと、スクリプトの使い方が分かりません。

**Comment by mattn** [comment]
スクリプトはプロジェクトルートで開いて `:so` でお願いします。

**Comment by k-takata** [comment]
スクリプトの先頭に使い方をつっこんでおきました。

**Comment by mattn** [comment]
ありがとうございます。
