### ISSUE TITLE
Delect code language

### ISSUE THREAD

**Issue by mattn** [vim-jp/vim-users-jp#8]
http://vim-jp.org/vim-users-jp/2009/05/27/Hack-17.html
http://vim-jp.org/vim-users-jp/2009/06/22/Hack-30.html
http://vim-jp.org/vim-users-jp/2009/06/26/Hack-32.html
http://vim-jp.org/vim-users-jp/2009/07/02/Hack-35.html

見つけ次第追加予定

hack 44 あたりまではチェックした。

誰か手伝ってもいいよーって人、時間あったら続きお願いします。

**Comment by k-takata** [comment]
http://vim-jp.org/vim-users-jp/2009/09/18/Hack-74.html
「autocmdの定義」の部分のコードが code="lang-vim" になっていません。

**Comment by mattn** [comment]
done. 他も反映しました。

https://github.com/vim-jp/vim-users-jp/commit/c39e60b6dac4eaf1cb116ab893ef60d846ef4be8
